### ISSUE TITLE
Invalid arg type

### ISSUE THREAD

**Issue by ghost** [csgofloat/inspect#81]
Error:

`(node:14312) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
debug: Fetched items_game_cdn.txt
debug: Fetched schema.json
internal/fs/utils.js:781
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (68)
    at Object.writeFile (fs.js:1436:5)
    at FileStorage.saveFile.FileStorage.writeFile (C:\Users\makez\Desktop\Code\test\csgofloat\node_modules\file-manager\index.js:68:5)
    at SteamUser._handlers.<computed> (C:\Users\makez\Desktop\Code\test\csgofloat\node_modules\steam-user\components\logon.js:294:18)
    at SteamUser._handleMessage (C:\Users\makez\Desktop\Code\test\csgofloat\node_modules\steam-user\components\messages.js:249:30)
    at CMClient.emit (events.js:327:22)
    at CMClient._netMsgReceived (C:\Users\makez\Desktop\Code\test\csgofloat\node_modules\steam-client\lib\cm_client.js:323:8)
    at CMClient.handlers.<computed> (C:\Users\makez\Desktop\Code\test\csgofloat\node_modules\steam-client\lib\cm_client.js:609:8)
    at CMClient._netMsgReceived (C:\Users\makez\Desktop\Code\test\csgofloat\node_modules\steam-client\lib\cm_client.js:305:24)
    at TCPConnection.emit (events.js:315:20)
    at TCPConnection._readPacket (C:\Users\makez\Desktop\Code\test\csgofloat\node_modules\steam-client\lib\tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by ValvojaX** [comment]
This happens with the latest version of node, I downgraded to an older one and it got fixed

**Comment by Step7750** [comment]
Thanks for the report! In the meantime, I'd recommend using the provided docker images which have a consistent version that is used in production on our end.
